### ISSUE TITLE
PPTX get error . JDK1.7 OFFICE 2016.

### ISSUE THREAD

**Issue by hubobbb** [marspie/marspie-officetrans#1]
12:10:13.304 INFO  com.marspie.rmi.launcher.ServerLauncher - Marspie office transfer server start.
12:10:21.352 INFO  com.marspie.rmi.office.OfficeTransService - Add Convert task source::e:\\3.pptx target::e:\\3.pptx.pdf officeType::PPT
12:10:21.358 INFO  com.marspie.trans.OfficeTransUtil - convertToPdf------e:\\3.pptx    PPT
12:10:21.359 INFO  com.jacob.office.Converter - Begin convert task
com.jacob.com.ComFailException: A COM exception has been encountered:
At Invoke of: Close
Description: 80020011 / 不支持集合。

	at com.jacob.com.Dispatch.invokev(Native Method)
	at com.jacob.com.Dispatch.invokev(Dispatch.java:625)
	at com.jacob.com.Dispatch.callN(Dispatch.java:453)
	at com.jacob.com.Dispatch.call(Dispatch.java:541)
	at com.jacob.office.PPTConverter.convertToPdf(PPTConverter.java:36)
	at com.jacob.office.Converter.run(Converter.java:47)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
12:10:23.480 ERROR com.jacob.office.Converter - convert office to pdf error::A COM exception has been encountered:
At Invoke of: Close
Description: 80020011 / 不支持集合。

12:10:23.481 INFO  com.jacob.office.Converter - Convert office to pdf finish.
12:12:21.358 ERROR com.marspie.trans.OfficeTransUtil - Convert timeout...use :: 120000 but not convert success!
12:12:21.358 INFO  com.marspie.trans.OfficeTransUtil - Convert result::false
12:12:21.358 INFO  com.marspie.trans.OfficeTransUtil - Convert finish used time::120001 ms

===============
环境
Apache Maven 3.5.0 
Maven home: C:\Users\Administrator\apache-maven-3.5.0\bin\..
Java version: 1.7.0_75, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.7.0_75\jre
Default locale: zh_CN, platform encoding: GBK
OS name: "windows server 2012 r2", version: "6.3", arch: "amd64", family: "windows"

**Comment by marspie** [comment]
@hubobbb  Its fixed
